/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useLoader, useFrame, useResource} from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'


export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/models/tree.glb')
  const [treeRef, tree] = useResource()
  useFrame(({mouse}) => {
    tree.rotation.z += 0.01
    console.log(mouse)
  })
  return (
    <group ref={group} {...props} dispose={null} position={[0,0,-50]}>
      <scene name="Scene">
      <mesh
          ref={treeRef}
          material={materials['palette.001']}
          geometry={nodes.tree.geometry}
          name="tree"
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh material={materials.Material} geometry={nodes.Cube.geometry} name="Cube" />
      </scene>
    </group>
  )
}
